### ISSUE TITLE
Implement pipeline for integration tests

### ISSUE THREAD

**Issue by Krisilda** [bwsw/kafka-reader#14]
1. Pipeline for receiving all messages without commit.

**Comment by MedvedevBW** [comment]
pipeline 1 steps:
1. Create producer wrapper
2. Put some records to Kafka
3. Create Consumer
4. Create CheckpointInfoProcessor with default  implementation
5. Create MessageQueue
6. Create EventHandler (mock implementation) with messageCount = count of writing records in step 2
7. Execute method 'handle' of EventHandle
8. Check retrieved list of OutputEnvelope for correctness:
  a. Create list with expected OutputEnvelop entities based on records from step 2
  b. Compare expected OutputEnvelope entities and retrieved OutputEnvelope entities
9. Execute method 'save' of CheckpointInfoProcessor
10. Close Consumer.
11. Repeat 3, 4, 5, 6, 7 steps
12. Check that list with retrieved OutputEnvelope entities is empty
