### ISSUE TITLE
Add code coverage into Jenkins job and set up reporting into GitHub

### ISSUE THREAD

**Issue by Krisilda** [bwsw/kafka-reader#17]
Change in code coverage should not fail build. 
The step should be after code style pass.

**Comment by MedvedevBW** [comment]
This task needs some tests in project for coverage report

**Comment by MedvedevBW** [comment]
1. add sbt scoverage plugin into project
2. add step for publish cobertura report in jenkins job

**Comment by MedvedevBW** [comment]
Implement in #8
