### ISSUE TITLE
Create sequence diagram

### ISSUE THREAD

**Issue by Krisilda** [bwsw/kafka-reader#2]

**Comment by MedvedevBW** [comment]
![seq](https://user-images.githubusercontent.com/25095225/32764990-01768d80-c93b-11e7-8e0b-b287d6dc3b74.png)

**Comment by MedvedevBW** [comment]
![sequence_diagram](https://user-images.githubusercontent.com/25095225/32765346-8b1e41a8-c93c-11e7-87a9-f6b9cd49b281.png)

**Comment by MedvedevBW** [comment]
https://drive.google.com/a/bw-sw.com/file/d/1GnLMP61DmxYcbO4WilHoIw7ZgHl8zxGh/view?usp=sharing
