### ISSUE TITLE
Find appropriate graphical editor for creating diagrams

### ISSUE THREAD

**Issue by Krisilda** [bwsw/kafka-reader#22]
App should provide work with drafts which can be edited after any time. 
App should provide enough tools and settings to draw class diagrams and diagrams of a sequence. 
Good to have - possibility to share drafts and diagrams using access rights.

**Comment by MedvedevBW** [comment]
draw.io Diagrams application from GoogleDrive:
https://drive.google.com/open?id=1GnLMP61DmxYcbO4WilHoIw7ZgHl8zxGh
https://drive.google.com/open?id=14IrMwkNnl_ZlZCz90IihM2TEHderIPgc
