### ISSUE TITLE
Implement pipeline (with commits) for integration tests 

### ISSUE THREAD

**Issue by Krisilda** [bwsw/kafka-reader#25]
1. Pipeline for receiving all messages with commit - read the first half of all messages, make a commit, restart pipeline and read the second half of all messages.

**Comment by MedvedevBW** [comment]
1. Create producer wrapper
2. Put some records to Kafka
3. Create Consumer
4. Create CheckpointInfoProcessor with default implementation
5. Create MessageQueue
6. Create EventHandler (mock implementation) with messageCount = first part count of writing records in step 2 
7. Execute method 'handle' of EventHandle
8. Check retrieved list of OutputEnvelope for correctness:
    a. Create list with expected OutputEnvelop entities based on entities taken in step 6
    b. Compare expected OutputEnvelope entities and retrieved OutputEnvelope entities
9. Execute method 'save' of CheckpointInfoProcessor
10. Close Consumer.
11. Repeat 3, 4, 5 steps
12. Create EventHandler (mock implementation) with messageCount = second part count of writing records in step 2
13. Execute method 'handle' of EventHandle
14. Check retrieved list of OutputEnvelope for correctness:
    a. Create list with expected OutputEnvelop entities based on entities taken in step 12
    b. Compare expected OutputEnvelope entities and retrieved OutputEnvelope entities
15. Execute method 'save' of CheckpointInfoProcessor
16. Repeat 3, 4, 5, 6, 7 steps
17. Check that list with retrieved OutputEnvelope entities is empty
