### ISSUE TITLE
Make a list of integration tests

### ISSUE THREAD

**Issue by Krisilda** [bwsw/kafka-reader#3]
@Krisilda commented on [Mon Nov 13 2017](https://github.com/bwsw/cs-simulator-kafka/issues/24)

Prepare a list of all features which should be tested. May include how will test each feature. 
Example of feature list for testing: 
1) read from topic
2) read from several topics
3) read from topic and write offset

**Comment by MedvedevBW** [comment]
https://docs.google.com/a/bw-sw.com/spreadsheets/d/1He3aUaepQ7DOOZO9R5x-gAY9m6zxtuhTd5RRk0vn7o0/edit?usp=sharing
