### ISSUE TITLE
Change publish step in CI 

### ISSUE THREAD

**Issue by Krisilda** [bwsw/kafka-reader#38]

**Comment by placccebo** [comment]
1) On a machine add `addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.0-M1")` to the file `~/.sbt/1.0/plugins/gpg.sbt`

**Comment by placccebo** [comment]
2. Run sbt
It will resolve dependency on sbt-pgp (download and install it)
To generate your own pair of keys do:
```bash
set pgpReadOnly := false
pgp-cmd gen-key
```

then type something like 'Mihaleva Ksenia', 'mikhaljova_ka@bw-sw.com', appropriatepassphrase

**Comment by placccebo** [comment]
3. Then we need to register keys here:
https://sks-keyservers.net/
by using command
```bash
pgp-cmd send-key <key id> hkp://pool.sks-keyservers.net (or hkp://keyserver.ubuntu.com)
```

The value of key id is one of the following:
- Hex Key ID
- “Name” of the key (e.g. “Mihaleva Ksenia” in the above example)
- “Email” of the key (e.g. “mikhaljova_ka@bw-sw.com” in the above example)

So you do:
```bash
pgp-cmd list-keys
```

Obtain 8d413ee2 (hex Key ID), and then
```bash
pgp-cmd send-key 8d413ee2 hkp://pool.sks-keyservers.net (or hkp://keyserver.ubuntu.com)
```

Soon thereafter you can check keys using a link::
https://gnupg.pub/

Finally, add the pgp passphrase to the global sbt settings:

```bash
echo "pgpPassphrase := Some(Array('p','a','s','s','p','h','r','a','s','e'))" >> ~/.sbt/(sbt-version 0.13 or 1.0)/global.sbt
```

**Comment by placccebo** [comment]
The wiki instruction is not fully automatic (there are manual steps which has been absent) and I'm going to try to fix it

**Comment by placccebo** [comment]
4) Use the following instruction to add Sonatype credentials (http://www.scala-sbt.org/1.x/docs/Using-Sonatype.html#Second+-+Configure+Sonatype+integration): 

5) Publish automatically
Add to project file `project/plugins.sbt` line `addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "<last version>")`. For more info, see: https://github.com/xerial/sbt-sonatype

6) Then you should publish GPG-signed artifacts to Sonatype: 
```bash
$ sbt publishSigned
```
7) Do close and promote at once:
```bash
$ sbt sonatypeRelease
```
